{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "prefix = \"lidar-data\"\n",
    "bucket = \"sagemaker-us-east-1-224863548990\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "import sagemaker as sage\n",
    "\n",
    "sess = sage.Session()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "ename": "S3UploadFailedError",
     "evalue": "Failed to upload /tmp/pytorch-example/cifar-10-data/cifar-10-python.tar.gz to Lidar/Lidar-data/cifar-10-python.tar.gz: An error occurred (NoSuchBucket) when calling the CreateMultipartUpload operation: The specified bucket does not exist",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mNoSuchBucket\u001b[0m                              Traceback (most recent call last)",
      "File \u001b[0;32m~/miniconda3/envs/7643/lib/python3.9/site-packages/boto3/s3/transfer.py:288\u001b[0m, in \u001b[0;36mS3Transfer.upload_file\u001b[0;34m(self, filename, bucket, key, callback, extra_args)\u001b[0m\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/boto3/s3/transfer.py?line=286'>287</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m--> <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/boto3/s3/transfer.py?line=287'>288</a>\u001b[0m     future\u001b[39m.\u001b[39;49mresult()\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/boto3/s3/transfer.py?line=288'>289</a>\u001b[0m \u001b[39m# If a client error was raised, add the backwards compatibility layer\u001b[39;00m\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/boto3/s3/transfer.py?line=289'>290</a>\u001b[0m \u001b[39m# that raises a S3UploadFailedError. These specific errors were only\u001b[39;00m\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/boto3/s3/transfer.py?line=290'>291</a>\u001b[0m \u001b[39m# ever thrown for upload_parts but now can be thrown for any related\u001b[39;00m\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/boto3/s3/transfer.py?line=291'>292</a>\u001b[0m \u001b[39m# client error.\u001b[39;00m\n",
      "File \u001b[0;32m~/miniconda3/envs/7643/lib/python3.9/site-packages/s3transfer/futures.py:103\u001b[0m, in \u001b[0;36mTransferFuture.result\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m     <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/s3transfer/futures.py?line=98'>99</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/s3transfer/futures.py?line=99'>100</a>\u001b[0m     \u001b[39m# Usually the result() method blocks until the transfer is done,\u001b[39;00m\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/s3transfer/futures.py?line=100'>101</a>\u001b[0m     \u001b[39m# however if a KeyboardInterrupt is raised we want want to exit\u001b[39;00m\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/s3transfer/futures.py?line=101'>102</a>\u001b[0m     \u001b[39m# out of this and propagate the exception.\u001b[39;00m\n\u001b[0;32m--> <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/s3transfer/futures.py?line=102'>103</a>\u001b[0m     \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_coordinator\u001b[39m.\u001b[39;49mresult()\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/s3transfer/futures.py?line=103'>104</a>\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mKeyboardInterrupt\u001b[39;00m \u001b[39mas\u001b[39;00m e:\n",
      "File \u001b[0;32m~/miniconda3/envs/7643/lib/python3.9/site-packages/s3transfer/futures.py:266\u001b[0m, in \u001b[0;36mTransferCoordinator.result\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/s3transfer/futures.py?line=264'>265</a>\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_exception:\n\u001b[0;32m--> <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/s3transfer/futures.py?line=265'>266</a>\u001b[0m     \u001b[39mraise\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_exception\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/s3transfer/futures.py?line=266'>267</a>\u001b[0m \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_result\n",
      "File \u001b[0;32m~/miniconda3/envs/7643/lib/python3.9/site-packages/s3transfer/tasks.py:139\u001b[0m, in \u001b[0;36mTask.__call__\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/s3transfer/tasks.py?line=137'>138</a>\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_transfer_coordinator\u001b[39m.\u001b[39mdone():\n\u001b[0;32m--> <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/s3transfer/tasks.py?line=138'>139</a>\u001b[0m         \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_execute_main(kwargs)\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/s3transfer/tasks.py?line=139'>140</a>\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mException\u001b[39;00m \u001b[39mas\u001b[39;00m e:\n",
      "File \u001b[0;32m~/miniconda3/envs/7643/lib/python3.9/site-packages/s3transfer/tasks.py:162\u001b[0m, in \u001b[0;36mTask._execute_main\u001b[0;34m(self, kwargs)\u001b[0m\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/s3transfer/tasks.py?line=159'>160</a>\u001b[0m logger\u001b[39m.\u001b[39mdebug(\u001b[39mf\u001b[39m\u001b[39m\"\u001b[39m\u001b[39mExecuting task \u001b[39m\u001b[39m{\u001b[39;00m\u001b[39mself\u001b[39m\u001b[39m}\u001b[39;00m\u001b[39m with kwargs \u001b[39m\u001b[39m{\u001b[39;00mkwargs_to_display\u001b[39m}\u001b[39;00m\u001b[39m\"\u001b[39m)\n\u001b[0;32m--> <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/s3transfer/tasks.py?line=161'>162</a>\u001b[0m return_value \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_main(\u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mkwargs)\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/s3transfer/tasks.py?line=162'>163</a>\u001b[0m \u001b[39m# If the task is the final task, then set the TransferFuture's\u001b[39;00m\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/s3transfer/tasks.py?line=163'>164</a>\u001b[0m \u001b[39m# value to the return value from main().\u001b[39;00m\n",
      "File \u001b[0;32m~/miniconda3/envs/7643/lib/python3.9/site-packages/s3transfer/tasks.py:348\u001b[0m, in \u001b[0;36mCreateMultipartUploadTask._main\u001b[0;34m(self, client, bucket, key, extra_args)\u001b[0m\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/s3transfer/tasks.py?line=346'>347</a>\u001b[0m \u001b[39m# Create the multipart upload.\u001b[39;00m\n\u001b[0;32m--> <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/s3transfer/tasks.py?line=347'>348</a>\u001b[0m response \u001b[39m=\u001b[39m client\u001b[39m.\u001b[39;49mcreate_multipart_upload(\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/s3transfer/tasks.py?line=348'>349</a>\u001b[0m     Bucket\u001b[39m=\u001b[39;49mbucket, Key\u001b[39m=\u001b[39;49mkey, \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mextra_args\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/s3transfer/tasks.py?line=349'>350</a>\u001b[0m )\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/s3transfer/tasks.py?line=350'>351</a>\u001b[0m upload_id \u001b[39m=\u001b[39m response[\u001b[39m'\u001b[39m\u001b[39mUploadId\u001b[39m\u001b[39m'\u001b[39m]\n",
      "File \u001b[0;32m~/miniconda3/envs/7643/lib/python3.9/site-packages/botocore/client.py:395\u001b[0m, in \u001b[0;36mClientCreator._create_api_method.<locals>._api_call\u001b[0;34m(self, *args, **kwargs)\u001b[0m\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/botocore/client.py?line=393'>394</a>\u001b[0m \u001b[39m# The \"self\" in this scope is referring to the BaseClient.\u001b[39;00m\n\u001b[0;32m--> <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/botocore/client.py?line=394'>395</a>\u001b[0m \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_make_api_call(operation_name, kwargs)\n",
      "File \u001b[0;32m~/miniconda3/envs/7643/lib/python3.9/site-packages/botocore/client.py:725\u001b[0m, in \u001b[0;36mBaseClient._make_api_call\u001b[0;34m(self, operation_name, api_params)\u001b[0m\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/botocore/client.py?line=723'>724</a>\u001b[0m     error_class \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mexceptions\u001b[39m.\u001b[39mfrom_code(error_code)\n\u001b[0;32m--> <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/botocore/client.py?line=724'>725</a>\u001b[0m     \u001b[39mraise\u001b[39;00m error_class(parsed_response, operation_name)\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/botocore/client.py?line=725'>726</a>\u001b[0m \u001b[39melse\u001b[39;00m:\n",
      "\u001b[0;31mNoSuchBucket\u001b[0m: An error occurred (NoSuchBucket) when calling the CreateMultipartUpload operation: The specified bucket does not exist",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mS3UploadFailedError\u001b[0m                       Traceback (most recent call last)",
      "\u001b[1;32m/home/chase/7643-Lidar/remoteDataDownload.ipynb Cell 3'\u001b[0m in \u001b[0;36m<cell line: 3>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      <a href='vscode-notebook-cell:/home/chase/7643-Lidar/remoteDataDownload.ipynb#ch0000002?line=0'>1</a>\u001b[0m WORK_DIRECTORY \u001b[39m=\u001b[39m \u001b[39m\"\u001b[39m\u001b[39m/tmp/pytorch-example/cifar-10-data\u001b[39m\u001b[39m\"\u001b[39m\n\u001b[0;32m----> <a href='vscode-notebook-cell:/home/chase/7643-Lidar/remoteDataDownload.ipynb#ch0000002?line=2'>3</a>\u001b[0m data_location \u001b[39m=\u001b[39m sess\u001b[39m.\u001b[39;49mupload_data(WORK_DIRECTORY, bucket\u001b[39m=\u001b[39;49mbucket, key_prefix\u001b[39m=\u001b[39;49mprefix)\n",
      "File \u001b[0;32m~/miniconda3/envs/7643/lib/python3.9/site-packages/sagemaker/session.py:233\u001b[0m, in \u001b[0;36mSession.upload_data\u001b[0;34m(self, path, bucket, key_prefix, extra_args)\u001b[0m\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/sagemaker/session.py?line=229'>230</a>\u001b[0m     s3 \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39ms3_resource\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/sagemaker/session.py?line=231'>232</a>\u001b[0m \u001b[39mfor\u001b[39;00m local_path, s3_key \u001b[39min\u001b[39;00m files:\n\u001b[0;32m--> <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/sagemaker/session.py?line=232'>233</a>\u001b[0m     s3\u001b[39m.\u001b[39;49mObject(bucket, s3_key)\u001b[39m.\u001b[39;49mupload_file(local_path, ExtraArgs\u001b[39m=\u001b[39;49mextra_args)\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/sagemaker/session.py?line=234'>235</a>\u001b[0m s3_uri \u001b[39m=\u001b[39m \u001b[39m\"\u001b[39m\u001b[39ms3://\u001b[39m\u001b[39m{}\u001b[39;00m\u001b[39m/\u001b[39m\u001b[39m{}\u001b[39;00m\u001b[39m\"\u001b[39m\u001b[39m.\u001b[39mformat(bucket, key_prefix)\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/sagemaker/session.py?line=235'>236</a>\u001b[0m \u001b[39m# If a specific file was used as input (instead of a directory), we return the full S3 key\u001b[39;00m\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/sagemaker/session.py?line=236'>237</a>\u001b[0m \u001b[39m# of the uploaded object. This prevents unintentionally using other files under the same\u001b[39;00m\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/sagemaker/session.py?line=237'>238</a>\u001b[0m \u001b[39m# prefix during training.\u001b[39;00m\n",
      "File \u001b[0;32m~/miniconda3/envs/7643/lib/python3.9/site-packages/boto3/s3/inject.py:318\u001b[0m, in \u001b[0;36mobject_upload_file\u001b[0;34m(self, Filename, ExtraArgs, Callback, Config)\u001b[0m\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/boto3/s3/inject.py?line=286'>287</a>\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mobject_upload_file\u001b[39m(\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/boto3/s3/inject.py?line=287'>288</a>\u001b[0m     \u001b[39mself\u001b[39m, Filename, ExtraArgs\u001b[39m=\u001b[39m\u001b[39mNone\u001b[39;00m, Callback\u001b[39m=\u001b[39m\u001b[39mNone\u001b[39;00m, Config\u001b[39m=\u001b[39m\u001b[39mNone\u001b[39;00m\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/boto3/s3/inject.py?line=288'>289</a>\u001b[0m ):\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/boto3/s3/inject.py?line=289'>290</a>\u001b[0m     \u001b[39m\"\"\"Upload a file to an S3 object.\u001b[39;00m\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/boto3/s3/inject.py?line=290'>291</a>\u001b[0m \n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/boto3/s3/inject.py?line=291'>292</a>\u001b[0m \u001b[39m    Usage::\u001b[39;00m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/boto3/s3/inject.py?line=315'>316</a>\u001b[0m \u001b[39m        transfer.\u001b[39;00m\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/boto3/s3/inject.py?line=316'>317</a>\u001b[0m \u001b[39m    \"\"\"\u001b[39;00m\n\u001b[0;32m--> <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/boto3/s3/inject.py?line=317'>318</a>\u001b[0m     \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mmeta\u001b[39m.\u001b[39;49mclient\u001b[39m.\u001b[39;49mupload_file(\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/boto3/s3/inject.py?line=318'>319</a>\u001b[0m         Filename\u001b[39m=\u001b[39;49mFilename,\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/boto3/s3/inject.py?line=319'>320</a>\u001b[0m         Bucket\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mbucket_name,\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/boto3/s3/inject.py?line=320'>321</a>\u001b[0m         Key\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mkey,\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/boto3/s3/inject.py?line=321'>322</a>\u001b[0m         ExtraArgs\u001b[39m=\u001b[39;49mExtraArgs,\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/boto3/s3/inject.py?line=322'>323</a>\u001b[0m         Callback\u001b[39m=\u001b[39;49mCallback,\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/boto3/s3/inject.py?line=323'>324</a>\u001b[0m         Config\u001b[39m=\u001b[39;49mConfig,\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/boto3/s3/inject.py?line=324'>325</a>\u001b[0m     )\n",
      "File \u001b[0;32m~/miniconda3/envs/7643/lib/python3.9/site-packages/boto3/s3/inject.py:143\u001b[0m, in \u001b[0;36mupload_file\u001b[0;34m(self, Filename, Bucket, Key, ExtraArgs, Callback, Config)\u001b[0m\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/boto3/s3/inject.py?line=107'>108</a>\u001b[0m \u001b[39m\"\"\"Upload a file to an S3 object.\u001b[39;00m\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/boto3/s3/inject.py?line=108'>109</a>\u001b[0m \n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/boto3/s3/inject.py?line=109'>110</a>\u001b[0m \u001b[39mUsage::\u001b[39;00m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/boto3/s3/inject.py?line=139'>140</a>\u001b[0m \u001b[39m    transfer.\u001b[39;00m\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/boto3/s3/inject.py?line=140'>141</a>\u001b[0m \u001b[39m\"\"\"\u001b[39;00m\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/boto3/s3/inject.py?line=141'>142</a>\u001b[0m \u001b[39mwith\u001b[39;00m S3Transfer(\u001b[39mself\u001b[39m, Config) \u001b[39mas\u001b[39;00m transfer:\n\u001b[0;32m--> <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/boto3/s3/inject.py?line=142'>143</a>\u001b[0m     \u001b[39mreturn\u001b[39;00m transfer\u001b[39m.\u001b[39;49mupload_file(\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/boto3/s3/inject.py?line=143'>144</a>\u001b[0m         filename\u001b[39m=\u001b[39;49mFilename,\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/boto3/s3/inject.py?line=144'>145</a>\u001b[0m         bucket\u001b[39m=\u001b[39;49mBucket,\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/boto3/s3/inject.py?line=145'>146</a>\u001b[0m         key\u001b[39m=\u001b[39;49mKey,\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/boto3/s3/inject.py?line=146'>147</a>\u001b[0m         extra_args\u001b[39m=\u001b[39;49mExtraArgs,\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/boto3/s3/inject.py?line=147'>148</a>\u001b[0m         callback\u001b[39m=\u001b[39;49mCallback,\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/boto3/s3/inject.py?line=148'>149</a>\u001b[0m     )\n",
      "File \u001b[0;32m~/miniconda3/envs/7643/lib/python3.9/site-packages/boto3/s3/transfer.py:294\u001b[0m, in \u001b[0;36mS3Transfer.upload_file\u001b[0;34m(self, filename, bucket, key, callback, extra_args)\u001b[0m\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/boto3/s3/transfer.py?line=288'>289</a>\u001b[0m \u001b[39m# If a client error was raised, add the backwards compatibility layer\u001b[39;00m\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/boto3/s3/transfer.py?line=289'>290</a>\u001b[0m \u001b[39m# that raises a S3UploadFailedError. These specific errors were only\u001b[39;00m\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/boto3/s3/transfer.py?line=290'>291</a>\u001b[0m \u001b[39m# ever thrown for upload_parts but now can be thrown for any related\u001b[39;00m\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/boto3/s3/transfer.py?line=291'>292</a>\u001b[0m \u001b[39m# client error.\u001b[39;00m\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/boto3/s3/transfer.py?line=292'>293</a>\u001b[0m \u001b[39mexcept\u001b[39;00m ClientError \u001b[39mas\u001b[39;00m e:\n\u001b[0;32m--> <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/boto3/s3/transfer.py?line=293'>294</a>\u001b[0m     \u001b[39mraise\u001b[39;00m S3UploadFailedError(\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/boto3/s3/transfer.py?line=294'>295</a>\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39mFailed to upload \u001b[39m\u001b[39m{}\u001b[39;00m\u001b[39m to \u001b[39m\u001b[39m{}\u001b[39;00m\u001b[39m: \u001b[39m\u001b[39m{}\u001b[39;00m\u001b[39m\"\u001b[39m\u001b[39m.\u001b[39mformat(\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/boto3/s3/transfer.py?line=295'>296</a>\u001b[0m             filename, \u001b[39m'\u001b[39m\u001b[39m/\u001b[39m\u001b[39m'\u001b[39m\u001b[39m.\u001b[39mjoin([bucket, key]), e\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/boto3/s3/transfer.py?line=296'>297</a>\u001b[0m         )\n\u001b[1;32m    <a href='file:///home/chase/miniconda3/envs/7643/lib/python3.9/site-packages/boto3/s3/transfer.py?line=297'>298</a>\u001b[0m     )\n",
      "\u001b[0;31mS3UploadFailedError\u001b[0m: Failed to upload /tmp/pytorch-example/cifar-10-data/cifar-10-python.tar.gz to Lidar/Lidar-data/cifar-10-python.tar.gz: An error occurred (NoSuchBucket) when calling the CreateMultipartUpload operation: The specified bucket does not exist"
     ]
    }
   ],
   "source": [
    "WORK_DIRECTORY = \"/tmp/pytorch-example/cifar-10-data\"\n",
    "\n",
    "data_location = sess.upload_data(WORK_DIRECTORY, bucket=bucket, key_prefix=prefix)"
   ]
  }
 ],
 "metadata": {
  "interpreter": {
   "hash": "830911f9e07924fa967a24f4831cada907fab13bf23513f03ad15f03bde45365"
  },
  "kernelspec": {
   "display_name": "Python 3.9.7 ('7643')",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
